namespace Peak.Can.Ccp
{
	public enum TCCPResult : uint
	{
		CCP_ERROR_ACKNOWLEDGE_OK = 0u,
		CCP_ERROR_DAQ_OVERLOAD = 1u,
		CCP_ERROR_CMD_PROCESSOR_BUSY = 16u,
		CCP_ERROR_DAQ_PROCESSOR_BUSY = 17u,
		CCP_ERROR_INTERNAL_TIMEOUT = 18u,
		CCP_ERROR_KEY_REQUEST = 24u,
		CCP_ERROR_SESSION_STS_REQUEST = 25u,
		CCP_ERROR_COLD_START_REQUEST = 32u,
		CCP_ERROR_CAL_DATA_INIT_REQUEST = 33u,
		CCP_ERROR_DAQ_LIST_INIT_REQUEST = 34u,
		CCP_ERROR_CODE_UPDATE_REQUEST = 35u,
		CCP_ERROR_UNKNOWN_COMMAND = 48u,
		CCP_ERROR_COMMAND_SYNTAX = 49u,
		CCP_ERROR_PARAM_OUT_OF_RANGE = 50u,
		CCP_ERROR_ACCESS_DENIED = 51u,
		CCP_ERROR_OVERLOAD = 52u,
		CCP_ERROR_ACCESS_LOCKED = 53u,
		CCP_ERROR_NOT_AVAILABLE = 54u,
		CCP_ERROR_PCAN = 2147483648u
	}
}
